---
- name: Deploy services on VMs
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == "Debian"

    - name: Set user home directory
      set_fact:
        ansible_user_home: "/{{ 'root' if ansible_user == 'root' else 'home/' + ansible_user }}"

    - name: create directory for this deployment
      file:
        path: "{{ ansible_user_home }}/{{ deployment_name }}"
        state: directory

    - name: create directory for postgres data
      file:
        path: "{{ pg_data_dir }}"
        state: directory
        owner: 1001
        group: 1001
    
    - name: create conf directory
      file:
        path: "{{ ansible_user_home }}/{{ deployment_name }}/conf"
        state: directory

    - name: copy nginx.conf
      template:
        src: "./conf/nginx.conf.j2"
        dest: "/{{ ansible_user_home }}/{{ deployment_name }}/conf/nginx.conf"

    - name: create directory for certificates
      file:
        path: "{{ ansible_user_home }}/{{ deployment_name }}/certs"
        state: directory

    - name: create directory for custom certificates
      file:
        path: "{{ ansible_user_home }}/{{ deployment_name }}/certs/custom/{{ hostvars[inventory_hostname]['domain'] }}"
        state: directory
      when: use_custom_certs

    - name: copy custom certificate fullchain
      template:
        src: "./certs/custom/{{ hostvars[inventory_hostname]['domain'] }}/fullchain.pem"
        dest: "{{ ansible_user_home }}/{{ deployment_name }}/certs/custom/{{ hostvars[inventory_hostname]['domain'] }}/fullchain.pem"
      when: use_custom_certs

    - name: copy custom certificate privkey
      template:
        src: "./certs/custom/{{ hostvars[inventory_hostname]['domain'] }}/privkey.pem"
        dest: "{{ ansible_user_home }}/{{ deployment_name }}/certs/custom/{{ hostvars[inventory_hostname]['domain'] }}/privkey.pem"
      when: use_custom_certs

    - name: Copy Docker Compose file
      template:
        src: "docker-compose.j2"
        dest: "/{{ ansible_user_home }}/{{ deployment_name }}/docker-compose.yml"
      delegate_to: "{{ inventory_hostname }}"

    - name: Start services with Docker Compose
      command: docker-compose up -d
      args:
        chdir: "/{{ ansible_user_home }}/{{ deployment_name }}"
      become_user: "{{ ansible_user }}"

  vars:
    pg_data_dir: "{{ ansible_user_home }}/{{ deployment_name }}/pg_data"

    

