all:
  hosts:
    pg-2:
      ansible_host: 138.68.188.149
      domain: pg2.abexamir.me
    pg-1:
      ansible_host: 138.68.178.97
      domain: pg1.abexamir.me

  vars:
    deployment_name: pg_kc_ha
    use_custom_certs: "yes"  # "yes" or "no", if "yes", you should provide certificates in certs directory
#    letsencrypt_email: "abexamir@gmail.com"
#    global_domain: "pg.abexamir.me" # the single entry point of the cluster
#    custom_docker_network_cidr: "10.143.0.0/16"
#    loadbalancer_mode: "tcp"


